;DEFINITIONS:
(DEFVAR LIST1 '(RM F G H J (J G D)))
(DEFVAR LIST2 '(2 3 4 5 6 (7 8)))
(DEFVAR LIST3 '(U N Y L O O P))

;TASK1:
(WRITE "Task 1 result: ")
(WRITE ((LAMBDA (LIST1 LIST2 LIST3) 
			(LIST(CAR LIST1)(CAR LIST2)(CAR LIST3))) 
		LIST1 LIST2 LIST3))

;TASK2:
(WRITE-LINE "")
(WRITE "Task 2 result: ")
(DEFUN TASK2 (LIST1 LIST2 LIST3) 
	(LIST (NTH 4 LIST1)(NTH 6 LIST2)(NTH 2 LIST3)))

(WRITE(TASK2 LIST1 LIST2 LIST3))

;TASK3:
(WRITE-LINE "")
(WRITE "Task 3 result: ")
(DEFUN TASK3 (ARG) 
	(IF (ATOM ARG)
		(IF (EQUAL (MOD ARG 2) 0) 
			(* ARG ARG) 
			(LOG 2 ARG))
		NIL))

(WRITE(TASK3 '(3 4)))