(DEFVAR LIST1 '(1 2 3 4 5 6 7 8 9))
(DEFVAR LIST2 '(5 4 6 7 8 9))
(DEFVAR LIST3 '(6 5 4 3 2 1))
(DEFVAR LIST4 '(9 8 7 6 5 4 3 2 1))
(DEFVAR LIST5 '(1 3 5 7))
(DEFVAR LIST6 '(2 4 6))
(DEFVAR LIST7 '(1 (2 (3 (4)) 2 (3)) 1 (2 (3 (4 (5 5))) 2 (3)) 1))
(DEFVAR LIST8 '((((((()))))())(((()))())))
(DEFVAR LIST9 '(-12 8 32 6 -4 4 3 1 1))


;Task 1:
;----------------------------------------------------
(DEFUN CHECK-INCREASE-SORTED (LST)
  	(COND ((NULL (CDR LST)) T)
  		((> (CAR LST) (CADR LST)) NIL)
      	((CHECK-INCREASE-SORTED (CDR LST)))
   	)
)
(DEFUN CHECK-DECREASE-SORTED (LST)
  	(COND ((NULL (CDR LST)) T)
  		((< (CAR LST) (CADR LST)) NIL)
      	((CHECK-DECREASE-SORTED(CDR LST)))
   	)
)
(DEFUN IS-SORTED (LST)
	(OR(CHECK-DECREASE-SORTED LST) (CHECK-INCREASE-SORTED LST))
)

;Task 2:




;Task 3:
;----------------------------------------------------
(DEFUN PUT-IN (LST X)
   (cond ((NULL LST) (LIST X))
        ((> (CAR LST) X) (CONS X LST))
        (T (CONS (CAR LST) (PUT-IN (CDR LST) X)))
    )
) 
(DEFUN INSERTION-SORT (X &OPTIONAL (S NIL))
   	(cond ((NULL X) S)
        (T (INSERTION-SORT (CDR X) (PUT-IN S (CAR X))))
   	)
)
(WRITE(INSERTION-SORT LIST9))

;Task 4:
;----------------------------------------------------
(DEFUN ASSOCIATION-DECREASE (LST1 LST2)
	(COND ((AND (NULL LST1) (NULL LST2)) NIL)
		((NULL LST1) (CONS (CAR LST2) (ASSOCIATION-DECREASE LST1 (CDR LST2))))
		((NULL LST2) (CONS (CAR LST1) (ASSOCIATION-DECREASE (CDR LST1) LST2)))
		((> (CAR LST1)(CAR LST2)) (CONS (CAR LST1) (ASSOCIATION-DECREASE (CDR LST1) LST2)))
		(T (CONS (CAR LST2) (ASSOCIATION-DECREASE LST1 (CDR LST2))))
	)
)
(DEFUN ASSOCIATION-INCREASE (LST1 LST2)
	(COND ((AND (NULL LST1) (NULL LST2)) NIL)
		((NULL LST1) (CONS (CAR LST2) (ASSOCIATION-INCREASE LST1 (CDR LST2))))
		((NULL LST2) (CONS (CAR LST1) (ASSOCIATION-INCREASE (CDR LST1) LST2)))
		((< (CAR LST1)(CAR LST2)) (CONS (CAR LST1) (ASSOCIATION-INCREASE (CDR LST1) LST2)))
		(T (CONS (CAR LST2) (ASSOCIATION-INCREASE LST1 (CDR LST2))))
	)
)
(DEFUN ASSOCIATION (LST1 LST2)
	(COND ((AND (ATOM LST1) (ATOM LST1)) NIL) 
		((AND (CHECK-DECREASE-SORTED LST1) (CHECK-DECREASE-SORTED LST2)) (ASSOCIATION-DECREASE LST1 LST2))
		((AND (CHECK-INCREASE-SORTED LST1) (CHECK-INCREASE-SORTED LST2)) (ASSOCIATION-INCREASE LST1 LST2))
		(T NIL)
	)
)
(WRITE(ASSOCIATION LIST6 LIST1))



;Task 5:
;----------------------------------------------------
(DEFUN DEEP (LST &OPTIONAL (INDEX -1))
	(COND ((NULL LST) (+ INDEX 1))
		((ATOM LST) INDEX)
		(T (MAX (DEEP (CAR LST) (+ INDEX 1)) (DEEP (CDR LST) INDEX)))
	) 
)
(WRITE (DEEP LIST8))